Ques 1. Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

In [21]:
arr = np.arange(2,51,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# 

Ques 2. Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [25]:
import numpy as np
list1 = []
for i in range(5):
    x=int(input("Input : "))
    list1.append(x)
print(list1)
print()

list2 = []
for j in range(5):
    y = int(input("Input : "))
    list2.append(j)
print(list2)
print()


arr1 = np.array(list1)
arr2 = np.array(list2)
print(arr1)
print(arr2)
print()

arr3 = np.concatenate((arr1,arr2))
print(arr3)
print()

np.sort(arr3)



Input : 9
Input : 7
Input : 5
Input : 3
Input : 1
[9, 7, 5, 3, 1]

Input : 2
Input : 4
Input : 6
Input : 8
Input : 11
[0, 1, 2, 3, 4]

[9 7 5 3 1]
[0 1 2 3 4]

[9 7 5 3 1 0 1 2 3 4]



array([0, 1, 1, 2, 3, 3, 4, 5, 7, 9])

# 

Ques 3. Write a code snippet to find the dimensions of a ndarray and its size.

In [8]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(np.shape(arr))
np.size(arr)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


8

In [19]:
arr1 = np.ndarray([3,2,2])
print(arr1)
print(np.ndim(arr1))
np.size(arr1)

[[[6.23042070e-307 4.67296746e-307]
  [1.69121096e-306 1.33511018e-306]]

 [[7.56593017e-307 7.56599807e-307]
  [8.90104239e-307 1.24610383e-306]]

 [[1.69118108e-306 9.34608432e-307]
  [1.42410974e-306 8.34443015e-308]]]
3


12

# 

Ques 4. How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims.

In [28]:
arr_1d = np.array([1,2,3,4,5,6])
arr_2d = arr_1d[np.newaxis]
A2 = np.expand_dims(arr_1d, axis=(1,2,3))


print(arr_1d)
print(arr_1d.shape)
print()
print(arr_2d)
print(arr_2d.shape)

[1 2 3 4 5 6]
(6,)

[[1 2 3 4 5 6]]
(1, 6)


# 

Ques 5. Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [6]:
import numpy as np
arr1 = np.array([[1,2],[4,3]])
arr2 = np.array([[9,8],[5,6]])

print("Vertical Stack")
print(np.vstack((arr1,arr2)))
print()
print("Horizontal Stack")
print(np.hstack((arr1,arr2)))

Vertical Stack
[[1 2]
 [4 3]
 [9 8]
 [5 6]]

Horizontal Stack
[[1 2 9 8]
 [4 3 5 6]]


# 

Ques 6. How to get unique items and counts of unique items?

In [9]:
x = np.array([1,2,3,4,9,8,76,12,15,63,22,30,19,1,2,2,2,1,76,22])
unique, count = np.unique(x, return_counts = True)
print("Unique Items:",unique)
print("Unique Items Count:",count)

Unique Items: [ 1  2  3  4  8  9 12 15 19 22 30 63 76]
Unique Items Count: [3 4 1 1 1 1 1 1 1 2 1 1 2]
